server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

spring:
  application:
    name: ice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoqi-juhao/Lyh
          search-paths: src/main/resources
          username: xiaoqi-juhao
          password: 512823qixue
